# Generated by Django 2.2.2 on 2019-07-26 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.CharField(max_length=255)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
